site_name: Samskritakendram-SBUSA

nav:
    - Home: index.md
    - Performances : ./performances.md
    - Inspirational: ./inspirational.md
    - Resources: ./resources.md

theme: material

use_directory_urls: true
